* [[https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][Publishing Org-mode files to HTML]]

** Introduction

This Tutorial describes one of many ways to publishing Org-mode files to XHTML. We use the publishing mechanism to keep the *.html files separated from our *.org files and to access them via web browser. Simply exporting the Org-mode files to HTML would leave them in ~/org/.

The XHTML files we create will work every where, on any host, with or without network access, and even when accessed through the file:/// protocol. To achieve this goal, we use

  - no absolute paths in HTML,
  - no server side scripting to navigate our output directories,
  - no base element (which is optional as of XHTML 1.0 strict) and
  - no software, but emacs, Org-mode and a web browser.

All this means, we are able to check and use the result of work immediately, everywhere.

** Basics

Throughout this tutorial, let's assume that all our Org-mode files live beneath ~/org/ and we publish them to ~/public_html/.

Let's further assume you're already familiar with the note taking basics in org and able to add a little content to the Org-mode files we add to our project during this tutorial. Please add at least one headline to each of the files.

The first thing to do is to create the folder ~/org. This is where our notes files live. Inside ~/org/ we have a folder css/ for stylesheets and scripts, and a folder called img/ (guess what's in there).

The first file we add to that folder (and to subdirectories later on) is called index.org. This name was choosen, since Org will publish the files to those with the basename of the source file plus the extension .html 1. Thus *~/org/index.org* will once be *~/public_html/index.html* – the startpage.

Let's add another file and call it ~/org/remember.org. After adding a stylesheet, ~/org/ looks like this:

#+begin_src
~/org/
   |- css/
   |  `- stylesheet.css
   |- img/
   |- index.org
   `- remember.org
#+end_src

** Publishing the /org/ project
